spring:
  application:
    name: discodeit
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

discodeit:
  jwt:
    secret: ${JWT_SECRET:discodeit-jwt-secret-key-must-be-at-least-32-bytes}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:30m}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:7d}

  admin:
    enabled: ${DISCODEIT_ADMIN_ENABLED:true}
    username: ${DISCODEIT_ADMIN_USERNAME:admin}
    email: ${DISCODEIT_ADMIN_EMAIL:admin@discodeit.com}
    password: ${DISCODEIT_ADMIN_PASSWORD:admin1234}

  storage:
    type: ${STORAGE_TYPE:local} # local | s3 (기본값: local)
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}

    s3:
      region: ${AWS_S3_REGION:ap-northeast-2}
      bucket: ${AWS_S3_BUCKET:}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} # (기본값: 10분)

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  info:
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.2-M8
    java-version: 17
    spring-boot-version: 3.5.14
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: ${discodeit.storage.type}
      path: ${discodeit.storage.local.root-path}
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size}
      max-request-size: ${spring.servlet.multipart.max-request-size}
